// Code generated by bpf2go; DO NOT EDIT.
//go:build (mips || mips64 || ppc64 || s390x) && linux

package main

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type flowSessionKey struct {
	_     structs.HostLayout
	Ip1   uint32
	Ip2   uint32
	Port1 uint16
	Port2 uint16
	Proto uint8
	_     [3]byte
}

type flowSessionVal struct {
	_        structs.HostLayout
	BytesAb  uint64
	BytesBa  uint64
	LastSeen uint64
}

// loadFlow returns the embedded CollectionSpec for flow.
func loadFlow() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_FlowBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load flow: %w", err)
	}

	return spec, err
}

// loadFlowObjects loads flow and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*flowObjects
//	*flowPrograms
//	*flowMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadFlowObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadFlow()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// flowSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type flowSpecs struct {
	flowProgramSpecs
	flowMapSpecs
	flowVariableSpecs
}

// flowProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type flowProgramSpecs struct {
	FlowIngress *ebpf.ProgramSpec `ebpf:"flow_ingress"`
}

// flowMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type flowMapSpecs struct {
	Sessions *ebpf.MapSpec `ebpf:"sessions"`
}

// flowVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type flowVariableSpecs struct {
}

// flowObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadFlowObjects or ebpf.CollectionSpec.LoadAndAssign.
type flowObjects struct {
	flowPrograms
	flowMaps
	flowVariables
}

func (o *flowObjects) Close() error {
	return _FlowClose(
		&o.flowPrograms,
		&o.flowMaps,
	)
}

// flowMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadFlowObjects or ebpf.CollectionSpec.LoadAndAssign.
type flowMaps struct {
	Sessions *ebpf.Map `ebpf:"sessions"`
}

func (m *flowMaps) Close() error {
	return _FlowClose(
		m.Sessions,
	)
}

// flowVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadFlowObjects or ebpf.CollectionSpec.LoadAndAssign.
type flowVariables struct {
}

// flowPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadFlowObjects or ebpf.CollectionSpec.LoadAndAssign.
type flowPrograms struct {
	FlowIngress *ebpf.Program `ebpf:"flow_ingress"`
}

func (p *flowPrograms) Close() error {
	return _FlowClose(
		p.FlowIngress,
	)
}

func _FlowClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed flow_bpfeb.o
var _FlowBytes []byte
