// Code generated by bpf2go; DO NOT EDIT.
//go:build (386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm) && linux

package main

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type dnsmarkDomainKey struct {
	_    structs.HostLayout
	Name [64]int8
}

type dnsmarkLpmKey struct {
	_         structs.HostLayout
	Prefixlen uint32
	Ip        [4]uint8
}

// loadDnsmark returns the embedded CollectionSpec for dnsmark.
func loadDnsmark() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_DnsmarkBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load dnsmark: %w", err)
	}

	return spec, err
}

// loadDnsmarkObjects loads dnsmark and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*dnsmarkObjects
//	*dnsmarkPrograms
//	*dnsmarkMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadDnsmarkObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadDnsmark()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// dnsmarkSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type dnsmarkSpecs struct {
	dnsmarkProgramSpecs
	dnsmarkMapSpecs
	dnsmarkVariableSpecs
}

// dnsmarkProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type dnsmarkProgramSpecs struct {
	DnsMark *ebpf.ProgramSpec `ebpf:"dns_mark"`
}

// dnsmarkMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type dnsmarkMapSpecs struct {
	CidrRules   *ebpf.MapSpec `ebpf:"cidr_rules"`
	DomainRules *ebpf.MapSpec `ebpf:"domain_rules"`
}

// dnsmarkVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type dnsmarkVariableSpecs struct {
}

// dnsmarkObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadDnsmarkObjects or ebpf.CollectionSpec.LoadAndAssign.
type dnsmarkObjects struct {
	dnsmarkPrograms
	dnsmarkMaps
	dnsmarkVariables
}

func (o *dnsmarkObjects) Close() error {
	return _DnsmarkClose(
		&o.dnsmarkPrograms,
		&o.dnsmarkMaps,
	)
}

// dnsmarkMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadDnsmarkObjects or ebpf.CollectionSpec.LoadAndAssign.
type dnsmarkMaps struct {
	CidrRules   *ebpf.Map `ebpf:"cidr_rules"`
	DomainRules *ebpf.Map `ebpf:"domain_rules"`
}

func (m *dnsmarkMaps) Close() error {
	return _DnsmarkClose(
		m.CidrRules,
		m.DomainRules,
	)
}

// dnsmarkVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadDnsmarkObjects or ebpf.CollectionSpec.LoadAndAssign.
type dnsmarkVariables struct {
}

// dnsmarkPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadDnsmarkObjects or ebpf.CollectionSpec.LoadAndAssign.
type dnsmarkPrograms struct {
	DnsMark *ebpf.Program `ebpf:"dns_mark"`
}

func (p *dnsmarkPrograms) Close() error {
	return _DnsmarkClose(
		p.DnsMark,
	)
}

func _DnsmarkClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed dnsmark_bpfel.o
var _DnsmarkBytes []byte
